<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.banking.automation</groupId>
	<artifactId>banking-automation-framework</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>Banking</name>

<properties>
	<!-- Java -->
    <java.version>17</java.version>
    <maven.compiler.release>${java.version}</maven.compiler.release>

    <!-- Automation -->
    <selenium.version>4.45.0</selenium.version>
    <testng.version>7.12.0</testng.version>
    <webdrivermanager.version>6.3.4</webdrivermanager.version>

    <!-- Reporting -->
    <allure.version>2.35.4</allure.version>

    <!-- Logging -->
    <log4j.version>2.26.0</log4j.version>

    <!-- Data -->
    <poi.version>5.5.1</poi.version>
    <jackson.version>2.22.0</jackson.version>

    <!-- API -->
    <rest-assured.version>6.0.0</rest-assured.version>

    <!-- Maven Plugins -->
    <maven.compiler.plugin.version>3.14.1</maven.compiler.plugin.version>
    <maven.surefire.plugin.version>3.5.4</maven.surefire.plugin.version>

    <!-- Encoding -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
</properties>

<dependencies>
	<!-- Selenium -->
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>${selenium.version}</version>
    </dependency>

    <!-- WebDriver Management -->
    <dependency>
        <groupId>io.github.bonigarcia</groupId>
        <artifactId>webdrivermanager</artifactId>
        <version>${webdrivermanager.version}</version>
    </dependency>

    <!-- TestNG -->
    <dependency>
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
        <version>${testng.version}</version>
        <scope>test</scope>
    </dependency>

    <!-- Allure -->
    <dependency>
        <groupId>io.qameta.allure</groupId>
        <artifactId>allure-testng</artifactId>
        <version>${allure.version}</version>
        <scope>test</scope>
    </dependency>

    <!-- Log4j API -->
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-api</artifactId>
        <version>${log4j.version}</version>
    </dependency>

    <!-- Log4j Implementation -->
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>${log4j.version}</version>
    </dependency>

    <!-- Apache POI -->
    <dependency>
        <groupId>org.apache.poi</groupId>
        <artifactId>poi-ooxml</artifactId>
        <version>${poi.version}</version>
    </dependency>

    <!-- Jackson -->
    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>${jackson.version}</version>
    </dependency>

    <!-- REST Assured -->
    <dependency>
        <groupId>io.rest-assured</groupId>
        <artifactId>rest-assured</artifactId>
        <version>${rest-assured.version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>

<build>
	<plugins>
	
	    <!-- Java Compiler -->
	    <plugin>
	        <groupId>org.apache.maven.plugins</groupId>
	        <artifactId>maven-compiler-plugin</artifactId>
	        <version>${maven.compiler.plugin.version}</version>
	        <configuration>
	            <release>${maven.compiler.release}</release>
	        </configuration>
	    </plugin>
	
	    <!-- Test Execution -->
	    <plugin>
	        <groupId>org.apache.maven.plugins</groupId>
	        <artifactId>maven-surefire-plugin</artifactId>
	        <version>${maven.surefire.plugin.version}</version>
	        <configuration>
	            <useModulePath>false</useModulePath>
	        </configuration>
	    </plugin>

	</plugins>
</build>
</project>